### ISSUE TITLE
Error recovery for network connections does not work in PSMB client

### ISSUE THREAD

**Issue by keuin** [keuin/crosslink#1]
If the network connection, say, is interrupted, the mod won't try to reconnect to the broker.

```
[00:37:27 ERROR] [crosslink.endpoint.psmb.***,bc.crosslink.pub]: Cannot publish message
java.net.SocketException: Broken pipe
        at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
        at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
        at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
        at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
        at java.io.DataOutputStream.write(DataOutputStream.java:112) ~[?:?]
        at java.io.FilterOutputStream.write(FilterOutputStream.java:108) ~[?:?]
        at com.keuin.psmb4j.BaseClient.keepAlive(BaseClient.java:81) ~[?:?]
        at com.keuin.crosslink.messaging.endpoint.remote.psmb.PsmbEndpoint.publish(PsmbEndpoint.java:88) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[00:37:27 INFO] [crosslink.endpoint.psmb.***,bc.crosslink.pub]: Thread is stopping.
[00:37:27 ERROR]: Exception in thread "Thread-13" java.lang.IllegalStateException: already connected
[00:37:27 ERROR]:       at com.keuin.psmb4j.BaseClient.connect(BaseClient.java:48)
[00:37:27 ERROR]:       at com.keuin.crosslink.messaging.endpoint.remote.psmb.PsmbEndpoint.publish(PsmbEndpoint.java:74)
[00:37:27 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by keuin** [comment]
https://github.com/keuin/crosslink/commit/9d57ce2517459ebe17cedaaa1662256d5a9271f1
